#!/usr/bin/env bash
# Build installable packages for a release.
#
#   ./package.sh                 .deb and .rpm for this machine's architecture
#   ./package.sh --all-arch      the same for amd64 *and* arm64
#   ./package.sh --arch amd64,arm64
#   ./package.sh --deb           only .deb, --rpm only .rpm
#   ./package.sh --no-container  never use podman to build the .rpm
#   ./package.sh --skip-build    package the binaries that are already built
#
# The binaries that go into a package are built from the musl targets, so they
# are statically linked: they run on any Linux of that architecture whatever
# its libc is, and the arm64 one can be built on an amd64 machine without a
# cross C toolchain.  See .cargo/config.toml and docs/packaging.md.
#
# The packages install the engine system wide - /usr/bin/ibus-telex and
# /usr/share/ibus/component/telex.xml - which is the directory IBus reads
# anyway, so `apt install ./ibus-telex_*.deb` or
# `dnf install ./ibus-telex-*.rpm` is the whole installation.
#
# Artifacts end up in dist/, together with SHA256SUMS for the release page.
set -euo pipefail

ROOT=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
NAME=ibus-telex
DIST=$ROOT/dist

WANT_DEB=0
WANT_RPM=0
SKIP_BUILD=0
CONTAINER=1
HOST_ARCH=$(dpkg --print-architecture 2>/dev/null || uname -m)
[ "$HOST_ARCH" = x86_64 ] && HOST_ARCH=amd64
[ "$HOST_ARCH" = aarch64 ] && HOST_ARCH=arm64
ARCHS=("$HOST_ARCH")

# amd64/arm64 -> cargo target, Debian architecture, RPM architecture
declare -A TARGET=([amd64]=x86_64-unknown-linux-musl [arm64]=aarch64-unknown-linux-musl)
declare -A DEB_ARCH=([amd64]=amd64 [arm64]=arm64)
declare -A RPM_ARCH=([amd64]=x86_64 [arm64]=aarch64)

usage() {
    sed -n '2,20p' "$ROOT/package.sh" | sed 's/^# \{0,1\}//'
}

while [ $# -gt 0 ]; do
    case "$1" in
        --deb) WANT_DEB=1 ;;
        --rpm) WANT_RPM=1 ;;
        --skip-build) SKIP_BUILD=1 ;;
        --no-container) CONTAINER=0 ;;
        --all-arch) ARCHS=(amd64 arm64) ;;
        --arch)
            shift
            [ $# -ge 1 ] || {
                echo "package.sh: --arch needs a list" >&2
                exit 2
            }
            IFS=, read -r -a ARCHS <<<"$1"
            ;;
        -h | --help)
            usage
            exit 0
            ;;
        *)
            echo "package.sh: unknown option $1" >&2
            usage >&2
            exit 2
            ;;
    esac
    shift
done

for arch in "${ARCHS[@]}"; do
    case "$arch" in
        amd64 | arm64) ;;
        *)
            echo "package.sh: unknown architecture $arch (amd64 or arm64)" >&2
            exit 2
            ;;
    esac
done

# No explicit choice means "everything that is possible".
if [ "$WANT_DEB" -eq 0 ] && [ "$WANT_RPM" -eq 0 ]; then
    WANT_DEB=1
    WANT_RPM=1
fi

log() { echo "==> $*"; }
warn() { echo "!!  $*" >&2; }

command -v cargo >/dev/null || {
    echo "package.sh: cargo not found - install Rust from https://rustup.rs" >&2
    exit 1
}

if [ "$SKIP_BUILD" -eq 0 ]; then
    for arch in "${ARCHS[@]}"; do
        triple=${TARGET[$arch]}
        if ! rustup target list --installed 2>/dev/null | grep -qx "$triple"; then
            log "rustup target add $triple"
            rustup target add "$triple"
        fi
        log "building for $arch ($triple)"
        cargo build --release --target "$triple" --manifest-path "$ROOT/Cargo.toml"
    done
fi

bin_for() {
    local arch=$1
    local bin=$ROOT/target/${TARGET[$arch]}/release/$NAME
    [ -x "$bin" ] || {
        echo "package.sh: no binary for $arch at $bin (run ./build.sh --$arch)" >&2
        exit 1
    }
    echo "$bin"
}

# The component file is generated by running `ibus-telex component`, and the
# binary for a foreign architecture cannot run here - so that one call uses a
# host build (the file only depends on the exec path).
helper_bin() {
    local helper=$ROOT/target/release/$NAME
    if [ ! -x "$helper" ] && [ "$SKIP_BUILD" -eq 0 ]; then
        cargo build --release --manifest-path "$ROOT/Cargo.toml" >/dev/null
    fi
    [ -x "$helper" ] || {
        echo "package.sh: need a host build to write the component file (run ./build.sh)" >&2
        exit 1
    }
    echo "$helper"
}

VERSION=$(sed -n 's/^version *= *"\(.*\)"/\1/p' "$ROOT/Cargo.toml" | head -1)
[ -n "$VERSION" ] || {
    echo "package.sh: cannot read the version from Cargo.toml" >&2
    exit 1
}
maintainer="${DEBFULLNAME:-$(git -C "$ROOT" config user.name 2>/dev/null || echo 'ibus-telex developers')} <${DEBEMAIL:-$(git -C "$ROOT" config user.email 2>/dev/null || echo 'ibus-telex@localhost')}>"
YEAR=$(date +%Y)

SHORT_DESC="Vietnamese input method engine for IBus (Telex/VNI)"
LONG_DESC="Vietnamese input method for IBus, written in Rust: Telex and VNI, tone
marks, đ, ư, ơ, ă, â, ê, ô, spell checking and automatic restore of words
that are not Vietnamese.  It speaks the IBus D-Bus protocol directly, so it
needs neither libibus nor any other C library.
.
Add the input source once per user account under
Settings -> Keyboard -> Input Sources -> Vietnamese -> Telex, then switch to
it with Super+Space."

POST_INSTALL_TEXT="
Add the input source once per user account:

    Settings -> Keyboard -> Input Sources -> Vietnamese -> Telex (Vietnamese)

Without a desktop settings dialog, the same thing from a terminal:

    ibus-telex sources --append     # prints the value to put in
    gsettings set org.gnome.desktop.input-sources sources '<that value>'

Then switch to it with Super+Space.
"

# only clear what is about to be rebuilt, so building one architecture does
# not throw away the artifacts of another
mkdir -p "$DIST"
[ "$WANT_DEB" -eq 1 ] && rm -f "$DIST"/*.deb
[ "$WANT_RPM" -eq 1 ] && rm -f "$DIST"/*.rpm
rm -f "$DIST"/SHA256SUMS

# ---------------------------------------------------------------- .deb
make_deb() {
    local arch=$1 bin=$2
    local stage=$DIST/pkg/deb-$arch
    log "building the .deb for $arch"
    mkdir -p "$stage/DEBIAN" \
        "$stage/usr/bin" \
        "$stage/usr/share/ibus/component" \
        "$stage/usr/share/doc/$NAME"

    install -Dm755 "$bin" "$stage/usr/bin/$NAME"
    "$(helper_bin)" component --exec "/usr/bin/$NAME" >"$stage/usr/share/ibus/component/telex.xml"
    install -Dm644 "$ROOT/README.md" "$stage/usr/share/doc/$NAME/README.md"
    git -C "$ROOT" log --no-decorate --date=short --pretty='%h %ad %s' 2>/dev/null |
        gzip -9n >"$stage/usr/share/doc/$NAME/changelog.gz" || true

    cat >"$stage/usr/share/doc/$NAME/copyright" <<EOF
Format: https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/
Upstream-Name: $NAME

Files: *
Copyright: $YEAR $maintainer
License: GPL-3.0-or-later
 On Debian systems the full text of the GNU General Public License version 3
 can be found in /usr/share/common-licenses/GPL-3.
EOF

    # A statically linked binary needs no libc and no libgcc; a dynamically
    # linked one needs the libc it was built against, which is read out of the
    # binary rather than guessed.
    local depends=ibus
    local glibc
    glibc=$(objdump -T "$bin" 2>/dev/null | grep -o 'GLIBC_[0-9.]*' | sort -uV | tail -1 | sed 's/^GLIBC_//' || true)
    if [ -n "$glibc" ]; then
        depends="libc6 (>= $glibc), libgcc-s1, ibus (>= 1.5.0)"
        log "$arch: needs glibc $glibc"
    else
        depends="ibus (>= 1.5.0)"
        log "$arch: statically linked, no libc dependency"
    fi

    # shipped files are 0644/0755, not whatever the umask left behind
    chmod -R u=rwX,go=rX "$stage/usr"

    local size indented
    size=$(du -sk --exclude=DEBIAN "$stage" | cut -f1)
    # every line after the first one of a control Description has to start
    # with a space, and a lone "." is a paragraph break
    indented=$(printf '%s\n' "$LONG_DESC" | sed 's/^/ /')

    cat >"$stage/DEBIAN/control" <<EOF
Package: $NAME
Version: $VERSION
Section: utils
Priority: optional
Architecture: ${DEB_ARCH[$arch]}
Depends: $depends
Installed-Size: $size
Maintainer: $maintainer
Description: $SHORT_DESC
$indented
EOF

    cat >"$stage/DEBIAN/postinst" <<EOF
#!/bin/sh
set -e
if command -v ibus >/dev/null 2>&1; then
    ibus write-cache --system >/dev/null 2>&1 || true
fi
echo "$POST_INSTALL_TEXT"
exit 0
EOF

    cat >"$stage/DEBIAN/postrm" <<'EOF'
#!/bin/sh
set -e
if command -v ibus >/dev/null 2>&1; then
    ibus write-cache --system >/dev/null 2>&1 || true
fi
exit 0
EOF

    chmod 755 "$stage/DEBIAN/postinst" "$stage/DEBIAN/postrm"
    local out="$DIST/${NAME}_${VERSION}_${DEB_ARCH[$arch]}.deb"
    dpkg-deb --build --root-owner-group "$stage" "$out" >/dev/null
    rm -rf "$stage"
    echo "    $out"
}

# ---------------------------------------------------------------- .rpm
write_spec() {
    local arch=$1 bin=$2 top=$3
    mkdir -p "$top/SPECS" "$top/SOURCES" "$top/BUILD" "$top/RPMS" "$top/SRPMS"
    install -Dm755 "$bin" "$top/SOURCES/$NAME"
    "$(helper_bin)" component --exec "/usr/bin/$NAME" >"$top/SOURCES/telex.xml"
    install -Dm644 "$ROOT/README.md" "$top/SOURCES/README.md"

    cat >"$top/SPECS/$NAME.spec" <<EOF
Name:           $NAME
Version:        $VERSION
Release:        1
Summary:        $SHORT_DESC
License:        GPL-3.0-or-later
Requires:       ibus >= 1.5.0
Source0:        $NAME
Source1:        telex.xml
Source2:        README.md

%description
$LONG_DESC

%prep

%build

%install
rm -rf %{buildroot}
install -Dm755 %{SOURCE0} %{buildroot}%{_bindir}/$NAME
install -Dm644 %{SOURCE1} %{buildroot}%{_datadir}/ibus/component/telex.xml
install -Dm644 %{SOURCE2} %{buildroot}%{_docdir}/$NAME/README.md

%post
if command -v ibus >/dev/null 2>&1; then
    ibus write-cache --system >/dev/null 2>&1 || :
fi
echo "$POST_INSTALL_TEXT"

%postun
if command -v ibus >/dev/null 2>&1; then
    ibus write-cache --system >/dev/null 2>&1 || :
fi

%files
%{_bindir}/$NAME
%{_datadir}/ibus/component/telex.xml
%{_docdir}/$NAME/README.md

%changelog
* $(LC_ALL=C date '+%a %b %d %Y') $maintainer - $VERSION-1
- $VERSION
EOF
}

make_rpm() {
    local arch=$1 bin=$2
    local top=$DIST/rpmbuild-$arch
    log "building the .rpm for $arch"
    write_spec "$arch" "$bin" "$top"

    if command -v rpmbuild >/dev/null; then
        rpmbuild -bb --target "${RPM_ARCH[$arch]}" --define "_topdir $top" \
            "$top/SPECS/$NAME.spec" >/dev/null
    elif [ "$CONTAINER" -eq 1 ] && command -v podman >/dev/null; then
        log "no rpmbuild here, using podman with a fedora image"
        podman run --rm -v "$top:/dist:rw" fedora:latest bash -c '
            set -e
            dnf -y install rpm-build >/dev/null
            rpmbuild -bb --target '"${RPM_ARCH[$arch]}"' --define "_topdir /dist" \
                /dist/SPECS/'"$NAME"'.spec >/dev/null
        '
    else
        warn "no rpmbuild and no podman: skipping the .rpm"
        warn "install rpm (apt install rpm) or podman, or use --deb"
        return 1
    fi

    local rpm
    rpm=$(find "$top/RPMS" -name '*.rpm' -print -quit)
    [ -n "$rpm" ] || {
        warn "the rpm build for $arch produced nothing"
        return 1
    }
    cp -- "$rpm" "$DIST/"
    rm -rf "$top"
    echo "    $DIST/$(basename "$rpm")"
}

status=0
for arch in "${ARCHS[@]}"; do
    bin=$(bin_for "$arch")
    if [ "$WANT_DEB" -eq 1 ]; then
        if command -v dpkg-deb >/dev/null; then
            make_deb "$arch" "$bin"
        else
            warn "dpkg-deb not found: skipping the .deb"
            status=1
        fi
    fi
    if [ "$WANT_RPM" -eq 1 ]; then
        make_rpm "$arch" "$bin" || true
    fi
done

# ------------------------------------------------------------- checksums
mapfile -t artifacts < <(find "$DIST" -maxdepth 1 -type f \( -name '*.deb' -o -name '*.rpm' \) | sort)
if [ "${#artifacts[@]}" -eq 0 ]; then
    warn "nothing was built"
    exit 1
fi
(cd "$DIST" && sha256sum "${artifacts[@]##*/}" >SHA256SUMS)

echo
log "artifacts in $DIST"
ls -1 "$DIST" | grep -v pkg | sed 's/^/    /'

deb=$(ls "$DIST" | grep '\.deb$' | head -1 || true)
rpm=$(ls "$DIST" | grep '\.rpm$' | head -1 || true)
cat <<EOF

Upload them, for example:

    gh release create v$VERSION --title "v$VERSION" --notes-from-tag dist/*.deb dist/*.rpm dist/SHA256SUMS

Anyone can then install with:
EOF
[ -n "$deb" ] && echo "    sudo apt install ./$deb"
[ -n "$rpm" ] && echo "    sudo dnf install ./$rpm"

exit "$status"
